### ISSUE TITLE
Not working in latest version of bakkesmod

### ISSUE THREAD

**Issue by justjakie** [segalll/DiscordRPCPlugin#5]
Upon trying to load the plugin within bakkesmod, it says the plugin is known to cause issues and will not be loaded until a fix is found (screenshot attached).
![RocketLeague_5y3qTma6wo](https://user-images.githubusercontent.com/80701672/161400795-e6d20166-3328-4e3f-92a7-ddc16672f1c3.png)

**Comment by RoguedBear** [comment]
a workaround i found to enable the plugin despite the warning: 
- go to bakkesmod plugin folder
- copy/paste the `DiscordRPCPlugin.dll` and rename that duplicate file to something else like `test.dll`
- then inside rocket league, open console (f6), and type `plugin load <your plugin name>`, so in my case `plugin load test`

the plugin would be loaded and RPC works in discord.
Though the devs must have disabled it for some reason, so i guess enable it at your own risk? Again, i havent found any issues caused by this plugin, so your mileage may vary

**Comment by segalll** [comment]
Yeah they blacklisted the plugin name because I hadn't updated it in a while, so it crashed on new maps. Not sure what to do about it.
